In [3]:
import pandas as pd 
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm, tree
from sklearn.model_selection import train_test_split


In [5]:
data  =  pd.read_csv("C:/Users/subar/Downloads/CMPE-255 Sec 99 - Data Mining/Home Works/HW3_Submission/IRIS.csv")

X  = data[['sepal_length','sepal_width','petal_length','petal_width']]
y= data['species']


In [6]:
#Split the Data into Training and Testing sets with test size as #30%
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, shuffle=True)

In [12]:
classifiers=[]
#SVM
model1 = svm.SVC()
classifiers.append(model1)

#Decision Tree
model2 = tree.DecisionTreeClassifier()
classifiers.append(model2)

#Random Forest
model3 = RandomForestClassifier()
classifiers.append(model3)

In [22]:
for clf in classifiers:
    clf.fit(X_train, y_train)
    y_pred= clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print("Accuracy of %s is: \n%s"%(clf, acc*100))
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix: \n%s"%(cm))
    print('***************************************')

Accuracy of SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False) is: 
97.77777777777777
Confusion Matrix: 
[[15  0  0]
 [ 0 16  1]
 [ 0  0 13]]
***************************************
Accuracy of DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best') is: 
97.77777777777777
Confusion Matrix: 
[[15  0  0]
 [ 0 16  1]
 [ 0  0 13]]
***************************************
Accuracy of RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
   

c:\users\subar\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
